import json
import csv
from pathlib import Path

# ── Script Logic ──────────────────────────────────────────────────────────────
# 1. Read endpoint/baseline.json generated by osqueryi
# 2. Run three hardening checks against the data:
#    - SIP: looks for '1' in the sip field (sip:1 = enabled)
#    - FileVault: checks if filevault field equals '1' (encrypted)
#    - Firewall: checks if firewall field is not '0' or missing (enabled)
# 3. Count passing checks and assign risk level:
#    - HIGH   = fewer than 2 controls passing
#    - MEDIUM = fewer than 3 controls passing
#    - LOW    = all 3 controls passing
# 4. Write results to endpoint/gap-report.csv (machine-readable)
# 5. Print summary to terminal with WARNING if any HIGH risk devices found
#
# In a real fleet this script would loop through hundreds of devices
# surfacing every machine out of compliance automatically — no manual
# review needed. Integrates with SIEM or ticketing via CSV output.
# ─────────────────────────────────────────────────────────────────────────────

CHECKS = [
    ('sip',       lambda d: '1' in str(d.get('sip', ''))),
    ('filevault', lambda d: d.get('filevault') == '1'),
    ('firewall',  lambda d: d.get('firewall') not in ('0', None)),
]

def assess(device: dict) -> dict:
    results = {}
    for key, fn in CHECKS:
        results[key] = fn(device)
    results['pass_count'] = sum(results[k] for k, _ in CHECKS)
    results['risk'] = (
        'HIGH'   if results['pass_count'] < 2 else
        'MEDIUM' if results['pass_count'] < 3 else
        'LOW'
    )
    return results

def main():
    src = Path('endpoint/baseline.json')
    if not src.exists():
        print('baseline.json not found — run osquery export first')
        return

    raw = json.loads(src.read_text())
    devices = raw if isinstance(raw, list) else [raw]

    rows = []
    for device in devices:
        result = assess(device)
        result['sip_raw']       = device.get('sip', 'missing')
        result['filevault_raw'] = device.get('filevault', 'missing')
        result['firewall_raw']  = device.get('firewall', 'missing')
        rows.append(result)

    out = Path('endpoint/gap-report.csv')
    fieldnames = ['sip', 'filevault', 'firewall', 'pass_count', 'risk',
                  'sip_raw', 'filevault_raw', 'firewall_raw']
    with out.open('w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f'Gap report written to {out}')
    print(f'Devices assessed: {len(rows)}')
    for row in rows:
        print(f'  Risk: {row["risk"]} | SIP: {row["sip"]} | '
              f'FileVault: {row["filevault"]} | Firewall: {row["firewall"]}')

    highs = [r for r in rows if r['risk'] == 'HIGH']
    if highs:
        print(f'WARNING: {len(highs)} HIGH risk device(s) found')

if __name__ == '__main__':
    main()
